import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'sbyan' at '7/6/17 4:06 PM' with Gradle 2.13
 *
 * @author sbyan, @date 7/6/17 4:06 PM
 */
public class ApplicationTest {
    @Test public void testSomeLibraryMethod() {
        Application classUnderTest = new Application();
        assertTrue("someLibraryMethod should return 'true'", true);
    }
}
